server:
  port: 9000
spring:
  application:
    name: coupon-gateway
eureka:
  client:
    service-url:
      # 需要向哪一个Eureka Server做服务发现或服务注册
      defaultZone: http://server1:8000/eureka/
zuul:
  prefix: /imooc
  routes:
    # 优惠券模板微服务路由配置定义
    template:
      path: /coupon-template/**
      # 向哪个服务进行转发
      serviceId: eureka-client-coupon-template
      # 是否跳过前缀
      strip-prefix: false
    # 优惠券分发微服务路由配置定义
    distribution:
      path: /coupon-distribution/**
      # 向哪个服务进行转发
      serviceId: eureka-client-coupon-distribution
      # 是否跳过前缀
      strip-prefix: false
    host:
      # 连接微服务超时时间
      connect-timeout-millis: 15000
      # socket超时时间
      socket-time-millis: 60000
# 负载均衡
ribbon:
  # 连接超时时间
  ConnectTimeout: 15000
  # 读取超时时间
  ReadTimeout: 15000
