spring:
  application:
    name: coupon-eureka
server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    # 标识是否从 Eureka Server 获取注册信息，默认是true，如果这是一个单节点的Eureka Server
    # 不需要同步其他节点的数据，设置为false
    fetch-registry: false
    # 是否将自己注册到 Eureka Server，默认是true，由于当前应用是单节点的 Eureka Server
    # 需要设置为 false
    register-with-eureka: false
    # 用于设置 Eureka Server所在地址，查询服务和注册服务都需要依赖这个地址
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 调节心跳连接比值
#    renewal-percent-threshold: 0.45
    # 关闭自我保护
    enable-self-preservation: false